### ISSUE TITLE
`pure` can give a matrix with the wrong dimensions

### ISSUE THREAD

**Issue by davidsd** [wchresta/matrix-static#2]
The `Applicative` instance for `Data.Matrix.Static.Matrix` appears to simply inherit the `Applicative` instance from `Data.Matrix.Matrix`:

https://github.com/wchresta/matrix-static/blob/25881369517e0db20cfb89461bec533bd6bb6962/src/Data/Matrix/Static.hs#L126

However, the `pure` implementation for `Data.Matrix.Matrix` just creates a 1 by 1 matrix:

http://hackage.haskell.org/package/matrix-0.3.6.1/docs/src/Data-Matrix.html#line-194

This seems to be a problem. (Forgive me if I missed something -- I have just been reading the code, and I haven't tested this issue.)

**Comment by davidsd** [comment]
Actually, it looks like the implementation of `<*>` from `Data.Matrix` is also incompatible with the types in `Data.Matrix.Static`. In particular, `<*>` of two matrices acts by tensoring and then flattening the matrices, leading to a bigger matrix.

It looks like `Data.Matrix.Static` should have a completely different `Applicative` instance that is not inherited from `Data.Matrix`.

**Comment by wchresta** [comment]
Thank you @davidsd , very well spotted! If you have a working solution for this, I'd be happy to merge it.
